user:
    type:     rest
    resource: AppBundle\Controller\UserController

product:
    type:     rest
    resource: AppBundle\Controller\ProductController

promotion:
    type:     rest
    resource: AppBundle\Controller\PromotionController
    
categorie:
    type:     rest
    resource: AppBundle\Controller\CategorieController
      
    

api_login_check:
    path: /api/login_check
