# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.serializer.product:
        class: AppBundle\Serializer\PictureSerializer
        arguments: [%route_picture_path%]
        tags:
            - { name: jms_serializer.event_subscriber }
