AppBundle\Entity\Product:
    exclusion_policy: ALL
    properties:
        label:
            expose: true
            type: string
        price:
            expose: true
            type: float
        description:
            expose: true
            type: string
        barCode:
            expose: true
            type: string
        virtual_properties:
            getCategoryId: 
                serialized_name: category_id
                type: integer
          
        guarantee:
            expose: true
            type: string
        picture:
            expose: true
            type: string
            
