AppBundle\Entity\Promotion:
    exclusion_policy: ALL
    properties:
        beginDate:
            expose: true
            type: DateTime<'d-m-Y'>
        endDate:
            expose: true
            type: DateTime<'d-m-Y'>
        newPrice:
            expose: true
        product:
            expose: true
        